import type { MaintenanceScheduleData } from "@/types/maintenance-schedule";

export const DUMMY_MAINTENANCE_SCHEDULE: MaintenanceScheduleData = {
  generatedAt: new Date().toISOString(),
  rows: [
    {
      id: "1",
      category: "Air Handling Units",
      assetCount: 38,
      frequency: {
        monthly: true,
        quarterly: true,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 3,
      totalEOPs: 1,
      totalSOPs: 2,
      mopRequirements: [
        { id: "mop-ahu-01", description: "MOP-AHU-01: Monthly filter inspection and replacement procedure", generated: true, documentUrl: "https://example.com/docs/mop-ahu-01.pdf" },
        { id: "mop-ahu-02", description: "MOP-AHU-02: Quarterly belt tension and lubrication procedure", generated: true, documentUrl: "https://example.com/docs/mop-ahu-02.pdf" },
        { id: "mop-ahu-03", description: "MOP-AHU-03: Annual coil cleaning and refrigerant charge verification", generated: false },
      ],
      eopRequirements: [
        { id: "eop-ahu-01", description: "EOP-AHU-01: Emergency shutdown and isolation procedure for AHU failure", generated: false },
      ],
      sopRequirements: [
        { id: "sop-ahu-01", description: "SOP-AHU-01: Standard startup and commissioning checklist", generated: true, documentUrl: "https://example.com/docs/sop-ahu-01.pdf" },
        { id: "sop-ahu-02", description: "SOP-AHU-02: Alarm response and escalation procedure", generated: false },
      ],
    },
    {
      id: "2",
      category: "Automatic Transfer Switches",
      assetCount: 9,
      frequency: {
        monthly: false,
        quarterly: true,
        semiAnnual: false,
        annual: true,
        twoYear: true,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 3,
      totalEOPs: 2,
      totalSOPs: 1,
      mopRequirements: [
        { id: "mop-ats-01", description: "MOP-ATS-01: Quarterly operation test under load with utility and generator", generated: true, documentUrl: "https://example.com/docs/mop-ats-01.pdf" },
        { id: "mop-ats-02", description: "MOP-ATS-02: Annual contact inspection, cleaning and torque verification", generated: false },
        { id: "mop-ats-03", description: "MOP-ATS-03: Bi-annual full maintenance overhaul and firmware update", generated: false },
      ],
      eopRequirements: [
        { id: "eop-ats-01", description: "EOP-ATS-01: Manual transfer procedure during utility failure", generated: true, documentUrl: "https://example.com/docs/eop-ats-01.pdf" },
        { id: "eop-ats-02", description: "EOP-ATS-02: ATS failure isolation and bypass to manual operation", generated: false },
      ],
      sopRequirements: [
        { id: "sop-ats-01", description: "SOP-ATS-01: Transfer sequence verification and logging procedure", generated: false },
      ],
    },
    {
      id: "3",
      category: "Backflow Preventers",
      assetCount: 4,
      frequency: {
        monthly: false,
        quarterly: false,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 1,
      totalEOPs: 0,
      totalSOPs: 1,
      mopRequirements: [
        { id: "mop-bfp-01", description: "MOP-BFP-01: Annual backflow preventer test, inspection and certification", generated: true, documentUrl: "https://example.com/docs/mop-bfp-01.pdf" },
      ],
      eopRequirements: [],
      sopRequirements: [
        { id: "sop-bfp-01", description: "SOP-BFP-01: Isolation and bypass procedure for backflow preventer servicing", generated: false },
      ],
    },
    {
      id: "4",
      category: "Building Management & Controls",
      assetCount: 3,
      frequency: {
        monthly: false,
        quarterly: true,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 2,
      totalEOPs: 1,
      totalSOPs: 2,
      mopRequirements: [
        { id: "mop-bms-01", description: "MOP-BMS-01: Quarterly BMS calibration and sensor verification", generated: false },
        { id: "mop-bms-02", description: "MOP-BMS-02: Annual control panel inspection and firmware update", generated: false },
      ],
      eopRequirements: [
        { id: "eop-bms-01", description: "EOP-BMS-01: BMS failure response and manual override procedure", generated: true, documentUrl: "https://example.com/docs/eop-bms-01.pdf" },
      ],
      sopRequirements: [
        { id: "sop-bms-01", description: "SOP-BMS-01: Set point adjustment and alarm threshold update procedure", generated: true, documentUrl: "https://example.com/docs/sop-bms-01.pdf" },
        { id: "sop-bms-02", description: "SOP-BMS-02: Trend data review and reporting procedure", generated: false },
      ],
    },
    {
      id: "5",
      category: "Condenser Units",
      assetCount: 55,
      frequency: {
        monthly: true,
        quarterly: false,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 2,
      totalEOPs: 1,
      totalSOPs: 1,
      mopRequirements: [
        { id: "mop-cdu-01", description: "MOP-CDU-01: Monthly coil inspection and cleaning procedure", generated: true, documentUrl: "https://example.com/docs/mop-cdu-01.pdf" },
        { id: "mop-cdu-02", description: "MOP-CDU-02: Annual refrigerant charge check and leak inspection", generated: true, documentUrl: "https://example.com/docs/mop-cdu-02.pdf" },
      ],
      eopRequirements: [
        { id: "eop-cdu-01", description: "EOP-CDU-01: Emergency refrigerant leak response and isolation procedure", generated: false },
      ],
      sopRequirements: [
        { id: "sop-cdu-01", description: "SOP-CDU-01: Seasonal startup and shutdown procedure", generated: true, documentUrl: "https://example.com/docs/sop-cdu-01.pdf" },
      ],
    },
    {
      id: "6",
      category: "Generators",
      assetCount: 6,
      frequency: {
        monthly: true,
        quarterly: true,
        semiAnnual: true,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 4,
      totalEOPs: 3,
      totalSOPs: 2,
      mopRequirements: [
        { id: "mop-gen-01", description: "MOP-GEN-01: Monthly no-load test run and visual inspection", generated: true, documentUrl: "https://example.com/docs/mop-gen-01.pdf" },
        { id: "mop-gen-02", description: "MOP-GEN-02: Quarterly load bank test and fuel system check", generated: true, documentUrl: "https://example.com/docs/mop-gen-02.pdf" },
        { id: "mop-gen-03", description: "MOP-GEN-03: Semi-annual coolant flush, filter and oil change", generated: false },
        { id: "mop-gen-04", description: "MOP-GEN-04: Annual full load test, battery replacement and AVR calibration", generated: false },
      ],
      eopRequirements: [
        { id: "eop-gen-01", description: "EOP-GEN-01: Generator failure response and load shedding procedure", generated: true, documentUrl: "https://example.com/docs/eop-gen-01.pdf" },
        { id: "eop-gen-02", description: "EOP-GEN-02: Fuel spill containment and emergency shutdown", generated: false },
        { id: "eop-gen-03", description: "EOP-GEN-03: Paralleling failure isolation procedure", generated: false },
      ],
      sopRequirements: [
        { id: "sop-gen-01", description: "SOP-GEN-01: Generator start-up and manual transfer checklist", generated: true, documentUrl: "https://example.com/docs/sop-gen-01.pdf" },
        { id: "sop-gen-02", description: "SOP-GEN-02: Fuel level monitoring and top-up procedure", generated: false },
      ],
    },
    {
      id: "7",
      category: "UPS Systems",
      assetCount: 22,
      frequency: {
        monthly: true,
        quarterly: true,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 3,
      totalEOPs: 2,
      totalSOPs: 2,
      mopRequirements: [
        { id: "mop-ups-01", description: "MOP-UPS-01: Monthly runtime test and battery health check", generated: false },
        { id: "mop-ups-02", description: "MOP-UPS-02: Quarterly static bypass test and internal inspection", generated: false },
        { id: "mop-ups-03", description: "MOP-UPS-03: Annual battery replacement and capacitor inspection", generated: false },
      ],
      eopRequirements: [
        { id: "eop-ups-01", description: "EOP-UPS-01: UPS overload and emergency bypass procedure", generated: false },
        { id: "eop-ups-02", description: "EOP-UPS-02: Critical load transfer to alternate feed upon UPS failure", generated: false },
      ],
      sopRequirements: [
        { id: "sop-ups-01", description: "SOP-UPS-01: Battery discharge test and data logging procedure", generated: false },
        { id: "sop-ups-02", description: "SOP-UPS-02: Alarm acknowledgment and escalation procedure", generated: false },
      ],
    },
    {
      id: "8",
      category: "Power Distribution Units",
      assetCount: 24,
      frequency: {
        monthly: true,
        quarterly: false,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 3,
      totalEOPs: 1,
      totalSOPs: 1,
      mopRequirements: [
        { id: "mop-pdu-01", description: "MOP-PDU-01: Monthly breaker and metering inspection", generated: true, documentUrl: "https://example.com/docs/mop-pdu-01.pdf" },
        { id: "mop-pdu-02", description: "MOP-PDU-02: Annual thermal imaging and torque verification", generated: true, documentUrl: "https://example.com/docs/mop-pdu-02.pdf" },
        { id: "mop-pdu-03", description: "MOP-PDU-03: Annual busbar cleaning and insulation resistance test", generated: true, documentUrl: "https://example.com/docs/mop-pdu-03.pdf" },
      ],
      eopRequirements: [
        { id: "eop-pdu-01", description: "EOP-PDU-01: PDU fault isolation and downstream load transfer procedure", generated: true, documentUrl: "https://example.com/docs/eop-pdu-01.pdf" },
      ],
      sopRequirements: [
        { id: "sop-pdu-01", description: "SOP-PDU-01: Circuit breaker trip investigation and reset procedure", generated: true, documentUrl: "https://example.com/docs/sop-pdu-01.pdf" },
      ],
    },
    {
      id: "9",
      category: "Cooling Towers",
      assetCount: 12,
      frequency: {
        monthly: true,
        quarterly: true,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: false,
      },
      totalMOPs: 3,
      totalEOPs: 1,
      totalSOPs: 2,
      mopRequirements: [
        { id: "mop-ct-01", description: "MOP-CT-01: Monthly water quality testing and chemical dosing", generated: true, documentUrl: "https://example.com/docs/mop-ct-01.pdf" },
        { id: "mop-ct-02", description: "MOP-CT-02: Quarterly drift eliminator and fill inspection", generated: false },
        { id: "mop-ct-03", description: "MOP-CT-03: Annual basin cleaning, fan and motor inspection", generated: false },
      ],
      eopRequirements: [
        { id: "eop-ct-01", description: "EOP-CT-01: Legionella outbreak response and emergency disinfection procedure", generated: false },
      ],
      sopRequirements: [
        { id: "sop-ct-01", description: "SOP-CT-01: Seasonal startup flushing and commissioning checklist", generated: true, documentUrl: "https://example.com/docs/sop-ct-01.pdf" },
        { id: "sop-ct-02", description: "SOP-CT-02: Water treatment chemical handling and dosing procedure", generated: false },
      ],
    },
    {
      id: "10",
      category: "Fire Suppression Systems",
      assetCount: 8,
      frequency: {
        monthly: false,
        quarterly: true,
        semiAnnual: false,
        annual: true,
        twoYear: false,
        threeYear: false,
        fiveYear: true,
      },
      totalMOPs: 2,
      totalEOPs: 2,
      totalSOPs: 3,
      mopRequirements: [
        { id: "mop-fss-01", description: "MOP-FSS-01: Quarterly agent level inspection and detector test", generated: false },
        { id: "mop-fss-02", description: "MOP-FSS-02: Annual full discharge test and cylinder recharge", generated: false },
      ],
      eopRequirements: [
        { id: "eop-fss-01", description: "EOP-FSS-01: System discharge response and area evacuation procedure", generated: false },
        { id: "eop-fss-02", description: "EOP-FSS-02: False discharge isolation and system reset procedure", generated: false },
      ],
      sopRequirements: [
        { id: "sop-fss-01", description: "SOP-FSS-01: System arming and disarming procedure for maintenance access", generated: false },
        { id: "sop-fss-02", description: "SOP-FSS-02: Pre-work hot-work permit and suppression system inhibit procedure", generated: false },
        { id: "sop-fss-03", description: "SOP-FSS-03: Inspection log completion and authority notification procedure", generated: false },
      ],
    },
  ],
};
